# Generated by Django 5.1 on 2024-09-05 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_userprofile_club_location_corporate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('phase', models.CharField(choices=[('announcement', 'Tournament Announcement and Promotion'), ('registration_open', 'Tournament Registration Open'), ('registration_close', 'Tournament Registration Close'), ('begin', 'Tournament Begin'), ('end', 'Tournament End'), ('ceremony', 'Tournament Ceremony')], default='announcement', max_length=20)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
