# Generated by Django 5.1 on 2024-09-05 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_tournament_is_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='is_visible',
        ),
    ]
